### ISSUE TITLE
Problem with method getPastSkyblockAuctions(string, long)

### ISSUE THREAD

**Issue by NertCoding** [mew/Slothpixel-JVM#1]
The slothpixel api does not take a long, but rather an int as the second parameter. In slothpixel.class, I found the following mistake:
`fun getPastSkyblockAuctions(itemId: String, from: Long = TimeUtil.yesterday(), to: Long = TimeUtil.now()): PastSkyblockAuctions {
        val jsonUrl = "$url/skyblock/auctions/$itemId?from=$from&to=$to"
        val json = getFromUrl(jsonUrl)
        return Gson().fromJson<PastSkyblockAuctions>(json, PastSkyblockAuctions::class.java)
    }`

If Long is changed to int, I believe it will work

**Comment by mew** [comment]
I think we already figured this out on Discord but if I'm thinking of someone else: according to the [official documentation](https://docs.slothpixel.me/#operation/getSkyblockAuctionItem) that endpoint takes a string (item id) and two [unix timestamps](https://en.wikipedia.org/wiki/Unix_time) (which would be longs).
