### ISSUE TITLE
slothpixel jvm dependency not found after compiling

### ISSUE THREAD

**Issue by alterie** [mew/Slothpixel-JVM#3]
I'm making mod that uses slothpixel jvm wrapper, but when I build it into a .jar file and run it, it gives me a `java.lang.NoClassDefFoundError: zone/nora/slothpixel/Slothpixel`. It works fine in eclipse but not as a jar.

**Comment by alterie** [comment]
My build.gradle:
https://gist.github.com/alterie/0b8e848f386bd40d892a7d71a2d76804

**Comment by alterie** [comment]
discord help me

**Comment by mew** [comment]
nice
